# Generated by Django 5.0.4 on 2026-01-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile_balance_project_buyers_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, help_text="YouTube video ssilkasini qo'ying", null=True),
        ),
    ]
