# Generated by Django 5.0.4 on 2026-01-03 07:36

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='project_thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_code/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(default='default.jpg', help_text="YouTube video ssilkasini qo'ying (Majburiy)"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_screenshots/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
