# Generated by Django 5.0.4 on 2026-01-04 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_sync_options_remove_profile_synced_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
