# Generated by Django 5.0.4 on 2026-01-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_profile_balance_deposit_transaction_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='deposit',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_receipts/'),
        ),
    ]
