# Generated by Django 5.0.4 on 2026-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_deposit_transaction_id_deposit_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
