# Generated by Django 5.0.4 on 2026-01-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_is_frozen_project_reports_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='security_status',
            field=models.CharField(choices=[('safe', 'Xavfsiz'), ('warning', 'Shubhali'), ('danger', 'Xavfli'), ('pending', 'Tekshirilmoqda')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='virustotal_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
