# Generated by Django 5.0.4 on 2026-01-24 05:08

import cloudinary_storage.storage
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_comment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_code',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_code/', validators=[projects.models.validate_file_size, projects.models.validate_file_extension]),
        ),
    ]
