# Generated by Django 5.0.4 on 2026-01-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Bildirishnoma olish uchun Telegram ID', max_length=50, null=True),
        ),
    ]
