# Generated by Django 5.0.4 on 2026-01-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_profile_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sync',
            options={},
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='message',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='click_trans_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(help_text="YouTube video ssilkasini qo'ying"),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
