# Generated by Django 5.0.4 on 2026-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_communitymessage_options_alter_sync_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Dasturlash'), ('mobile', 'Mobil Ilovalar'), ('ai', "Sun'iy Intellekt"), ('game', "O'yinlar"), ('desktop', 'Soft')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='security_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(),
        ),
    ]
