# Generated by Django 5.0.4 on 2026-01-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', "To'lab berildi"), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
    ]
