# Generated by Django 5.0.4 on 2026-01-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_withdrawal_status'),
    ]

    operations = [
    ]
