# Generated by Django 5.0.4 on 2026-01-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_trigram_extension'),
        ('projects', '0021_add_trigram_extension'),
    ]

    operations = [
    ]
