"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
import dj_database_url  # <--- YANGI QO'SHILDI (PostgreSQL uchun)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gknkdin(rj(n$xq7w=6ph=zs)nn7&%!*p5xyn$ul()8v^z+_3l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Renderdagi saytingiz nomini ham qo'shib qo'ysangiz yaxshi, hozircha '*' turaversin
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',                  # Admin panel dizayni (Eng tepada turishi kerak)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    # O'zingizning ilovalar
    'projects',

    # Google Login (Allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Allauth uchun kerak:
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # MUHIM: Dizayn ishlashi uchun pastdagi qator o'zgartirildi!
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# --- YANGI BAZA SOZLAMASI (PostgreSQL + SQLite) ---
DATABASES = {
    'default': dj_database_url.config(
        # Agar Renderda bo'lsa, PostgreSQL ishlatadi.
        # Agar kompyuterda bo'lsa, avtomatik SQLite ishlatadi.
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

SITE_ID = 1

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Renderda static fayllar ishlashi uchun kerak:
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media fayllar (Rasm/Video)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login/Logout yo'naltirishlari
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CLOUDINARY SOZLAMALARI ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'duy6grluh',
    'API_KEY': '929832358921299',
    'API_SECRET': 'u377zJ4qzYPM9uqKIM37bwspwv0'
}

# Media fayllar endi kompyuterga emas, Cloudinaryga tushadi
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'